/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;

/**
 *
 * @author Adri
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {
    BadConsequence pendingBCModel;
    
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }
    
    public void setPendingBadConsequence(BadConsequence bc){
        this.pendingBCModel = bc;
        boolean cond1, cond2, cond3, cond4;
        
        if (bc != null && !bc.isEmpty()){
            cond1 = bc.getNVisibleTreasures() != 0;
            cond2 = bc.getNHiddenTreasures() != 0;
            cond3 = !bc.getSpecificVisibleTreasures().isEmpty();
            cond4 = !bc.getSpecificHiddenTreasures().isEmpty();
            
            if (cond1 || cond2){
                this.tittle1.setText("Numero tesoros visibles");
                this.field1.setText(Integer.toString(bc.getNVisibleTreasures()));
                
                this.tittle2.setText("Numero tesoros ocultos");
                this.field2.setText(Integer.toString(bc.getNHiddenTreasures()));
                
                this.tittle1.setVisible(cond1);
                this.field1.setVisible(cond1);
                this.tittle2.setVisible(cond2);
                this.field2.setVisible(cond2);
            }
            else if (cond3 || cond4){
                this.tittle1.setText("Tesoros visibles");
                this.field1.setText(bc.getSpecificVisibleTreasures().toString());
                
                this.tittle2.setText("Tesoros ocultos");
                this.field2.setText(bc.getSpecificHiddenTreasures().toString());
                
                this.tittle1.setVisible(cond3);
                this.field1.setVisible(cond3);
                this.tittle2.setVisible(cond4);
                this.field2.setVisible(cond4);
            }
        }
        
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tittle1 = new javax.swing.JLabel();
        field1 = new javax.swing.JLabel();
        tittle2 = new javax.swing.JLabel();
        field2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel2");

        jLabel4.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tittle2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(tittle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(field2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tittle2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel field1;
    private javax.swing.JLabel field2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel tittle1;
    private javax.swing.JLabel tittle2;
    // End of variables declaration//GEN-END:variables
}
